/**
 * `akash deploy` command.
 *
 * Zero-config deployment to any platform. Auto-detects the target
 * (Vercel, Cloudflare, Netlify, Deno Deploy) or accepts explicit flags.
 * Generates platform-specific adapters and deploys.
 */

import { Command } from 'commander';
import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import pc from 'picocolors';

// --- Types ---

export type DeployTarget = 'vercel' | 'cloudflare' | 'netlify' | 'deno' | 'static' | 'node';

export interface DeployConfig {
  target: DeployTarget;
  outDir: string;
  ssr: boolean;
}

// --- Platform detection ---

/**
 * Auto-detect the deployment platform from project files and environment.
 */
export function detectPlatform(cwd: string): DeployTarget {
  // Check for platform-specific config files
  if (existsSync(join(cwd, 'vercel.json')) || process.env.VERCEL) {
    return 'vercel';
  }
  if (existsSync(join(cwd, 'wrangler.toml')) || existsSync(join(cwd, 'wrangler.jsonc'))) {
    return 'cloudflare';
  }
  if (existsSync(join(cwd, 'netlify.toml'))) {
    return 'netlify';
  }
  if (existsSync(join(cwd, 'deno.json')) || existsSync(join(cwd, 'deno.jsonc'))) {
    return 'deno';
  }
  // Default to static
  return 'static';
}

// --- Adapter generation ---

/**
 * Generate the entry point for a specific platform.
 */
export function generateAdapter(target: DeployTarget): string {
  switch (target) {
    case 'vercel':
      return `// Vercel serverless adapter — auto-generated by akash deploy
import { createServer } from './server.js';

export default async function handler(req, res) {
  const app = createServer();
  return app.handle(req, res);
}

export const config = { runtime: 'edge' };
`;

    case 'cloudflare':
      return `// Cloudflare Workers adapter — auto-generated by akash deploy
import { createServer } from './server.js';

export default {
  async fetch(request, env, ctx) {
    const app = createServer();
    return app.fetch(request);
  },
};
`;

    case 'netlify':
      return `// Netlify Functions adapter — auto-generated by akash deploy
import { createServer } from './server.js';

export async function handler(event, context) {
  const app = createServer();
  const response = await app.handle(event);
  return {
    statusCode: response.status,
    headers: Object.fromEntries(response.headers.entries()),
    body: await response.text(),
  };
}
`;

    case 'deno':
      return `// Deno Deploy adapter — auto-generated by akash deploy
import { createServer } from './server.js';

const app = createServer();
Deno.serve({ port: 8000 }, (request) => app.fetch(request));
`;

    case 'node':
      return `// Node.js adapter — auto-generated by akash deploy
import { createServer } from 'node:http';
import { createServer as createApp } from './server.js';

const app = createApp();
const server = createServer((req, res) => app.handle(req, res));
server.listen(process.env.PORT || 3000, () => {
  console.log('Server running on port ' + (process.env.PORT || 3000));
});
`;

    case 'static':
    default:
      return ''; // No adapter needed for static
  }
}

/**
 * Generate platform-specific config files.
 */
export function generatePlatformConfig(target: DeployTarget): Record<string, string> {
  const files: Record<string, string> = {};

  switch (target) {
    case 'vercel':
      files['vercel.json'] = JSON.stringify({
        buildCommand: 'npx akash build',
        outputDirectory: 'dist',
        framework: null,
      }, null, 2);
      break;

    case 'cloudflare':
      files['wrangler.toml'] = `name = "akash-app"
main = "dist/worker.js"
compatibility_date = "${new Date().toISOString().split('T')[0]}"

[site]
bucket = "./dist"
`;
      break;

    case 'netlify':
      files['netlify.toml'] = `[build]
  command = "npx akash build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
`;
      break;

    case 'deno':
      files['deno.json'] = JSON.stringify({
        tasks: {
          start: 'deno run --allow-net --allow-read dist/server.js',
          build: 'npx akash build',
        },
      }, null, 2);
      break;
  }

  return files;
}

// --- Deploy command ---

export function registerDeployCommand(program: Command): void {
  program
    .command('deploy')
    .description('Deploy to production (auto-detects platform)')
    .option('--target <platform>', 'Deploy target (vercel, cloudflare, netlify, deno, static, node)')
    .option('--ssr', 'Enable server-side rendering')
    .option('--no-build', 'Skip build step')
    .option('--dry-run', 'Generate config without deploying')
    .action(async (options: {
      target?: DeployTarget;
      ssr?: boolean;
      build: boolean;
      dryRun?: boolean;
    }) => {
      const cwd = process.cwd();
      const target = options.target ?? detectPlatform(cwd);

      console.log(pc.cyan(`\n  Deploying to ${pc.bold(target)}...\n`));

      // Build first
      if (options.build) {
        console.log(pc.dim('  Building for production...'));
        try {
          execSync('npx vite build', { cwd, stdio: 'inherit' });
        } catch {
          console.error(pc.red('\n  Build failed. Fix errors and try again.'));
          process.exit(1);
        }
      }

      // Generate adapter if SSR
      if (options.ssr && target !== 'static') {
        const adapter = generateAdapter(target);
        if (adapter) {
          const adapterPath = join(cwd, 'dist', 'adapter.js');
          writeFileSync(adapterPath, adapter, 'utf-8');
          console.log(pc.green(`  + dist/adapter.js (${target} adapter)`));
        }
      }

      // Generate platform config
      const configs = generatePlatformConfig(target);
      for (const [filename, content] of Object.entries(configs)) {
        const filepath = join(cwd, filename);
        if (!existsSync(filepath)) {
          writeFileSync(filepath, content, 'utf-8');
          console.log(pc.green(`  + ${filename}`));
        } else {
          console.log(pc.dim(`  ~ ${filename} (exists, skipped)`));
        }
      }

      if (options.dryRun) {
        console.log(pc.yellow('\n  Dry run — no deployment executed.\n'));
        return;
      }

      // Execute platform-specific deploy
      console.log(pc.cyan('\n  Deploying...\n'));

      try {
        switch (target) {
          case 'vercel':
            execSync('npx vercel --prod', { cwd, stdio: 'inherit' });
            break;
          case 'cloudflare':
            execSync('npx wrangler deploy', { cwd, stdio: 'inherit' });
            break;
          case 'netlify':
            execSync('npx netlify deploy --prod --dir=dist', { cwd, stdio: 'inherit' });
            break;
          case 'static':
            console.log(pc.green('  Static build ready in dist/'));
            console.log(pc.dim('  Upload dist/ to any static host (S3, GitHub Pages, etc.)'));
            break;
          default:
            console.log(pc.green(`  Build ready for ${target} in dist/`));
        }
        console.log(pc.green(pc.bold('\n  Deploy complete!\n')));
      } catch {
        console.error(pc.red('\n  Deploy failed. Check the logs above.'));
        process.exit(1);
      }
    });
}
