/**
 * Type-safe environment variables.
 *
 * Validates env vars at build time against a schema and generates
 * type declarations for `import.meta.env`.
 *
 * ```ts
 * // env.ts
 * import { defineEnv } from '@akashjs/vite-plugin/env';
 *
 * export const env = defineEnv({
 *   VITE_API_URL: { type: 'string', required: true },
 *   VITE_DEBUG: { type: 'boolean', default: false },
 *   VITE_MAX_RETRIES: { type: 'number', default: 3 },
 * });
 * ```
 */

// --- Types ---

export type EnvType = 'string' | 'number' | 'boolean';

export interface EnvFieldDef {
  type: EnvType;
  required?: boolean;
  default?: string | number | boolean;
  description?: string;
}

export type EnvSchema = Record<string, EnvFieldDef>;

export interface EnvValidationError {
  key: string;
  message: string;
}

export interface EnvValidationResult {
  valid: boolean;
  errors: EnvValidationError[];
  values: Record<string, string | number | boolean>;
}

// --- Validation ---

/**
 * Validate environment variables against a schema.
 */
export function validateEnv(
  schema: EnvSchema,
  envValues: Record<string, string | undefined>,
): EnvValidationResult {
  const errors: EnvValidationError[] = [];
  const values: Record<string, string | number | boolean> = {};

  for (const [key, def] of Object.entries(schema)) {
    const raw = envValues[key];

    // Check required
    if (raw === undefined || raw === '') {
      if (def.required) {
        errors.push({ key, message: `Missing required env variable: ${key}` });
        continue;
      }
      if (def.default !== undefined) {
        values[key] = def.default;
        continue;
      }
      continue;
    }

    // Parse type
    switch (def.type) {
      case 'string':
        values[key] = raw;
        break;

      case 'number': {
        const num = Number(raw);
        if (isNaN(num)) {
          errors.push({ key, message: `${key} must be a number, got: "${raw}"` });
        } else {
          values[key] = num;
        }
        break;
      }

      case 'boolean': {
        if (raw === 'true' || raw === '1') {
          values[key] = true;
        } else if (raw === 'false' || raw === '0' || raw === '') {
          values[key] = false;
        } else {
          errors.push({ key, message: `${key} must be a boolean, got: "${raw}"` });
        }
        break;
      }
    }
  }

  return { valid: errors.length === 0, errors, values };
}

// --- Type generation ---

/**
 * Generate TypeScript declarations for validated env variables.
 */
export function generateEnvTypes(schema: EnvSchema): string {
  let code = '// Auto-generated by @akashjs/vite-plugin — do not edit\n\n';
  code += "/// <reference types=\"vite/client\" />\n\n";
  code += 'interface ImportMetaEnv {\n';

  for (const [key, def] of Object.entries(schema)) {
    if (def.description) {
      code += `  /** ${def.description} */\n`;
    }
    const tsType = def.type === 'number' ? 'number'
      : def.type === 'boolean' ? 'boolean'
      : 'string';
    const optional = !def.required && def.default === undefined ? '?' : '';
    code += `  readonly ${key}${optional}: ${tsType};\n`;
  }

  code += '}\n\n';
  code += 'interface ImportMeta {\n';
  code += '  readonly env: ImportMetaEnv;\n';
  code += '}\n';

  return code;
}

// --- Runtime helper ---

/**
 * Define and validate env variables. Call at app startup.
 * Returns typed, validated values.
 */
export function defineEnv<T extends EnvSchema>(
  schema: T,
): { [K in keyof T]: T[K]['type'] extends 'number' ? number : T[K]['type'] extends 'boolean' ? boolean : string } {
  // In the browser, import.meta.env is available
  const envValues: Record<string, string | undefined> =
    typeof import.meta !== 'undefined' && (import.meta as any).env
      ? (import.meta as any).env
      : typeof process !== 'undefined'
        ? process.env as Record<string, string | undefined>
        : {};

  const result = validateEnv(schema, envValues);

  if (!result.valid) {
    const messages = result.errors.map((e) => `  - ${e.message}`).join('\n');
    throw new Error(`[AkashJS] Environment validation failed:\n${messages}`);
  }

  return result.values as any;
}
