/**
 * File-based route scanning and manifest generation.
 *
 * Scans `src/routes/` to build a route manifest for the virtual
 * module `virtual:akash-routes`. Also generates type definitions
 * for type-safe route params.
 */

import { existsSync, readdirSync, statSync } from 'node:fs';
import { join, relative, posix } from 'node:path';

// --- Types ---

export interface ScannedRoute {
  /** URL path pattern, e.g. '/blog/:slug' */
  path: string;
  /** Relative path to page.akash from routes dir */
  componentPath: string;
  /** Relative path to layout.akash, if present */
  layoutPath?: string;
  /** Relative path to loader.ts, if present */
  loaderPath?: string;
  /** Relative path to guard.ts, if present */
  guardPath?: string;
  /** Relative path to error.akash, if present */
  errorPath?: string;
  /** Child routes (from nested directories) */
  children: ScannedRoute[];
  /** Extracted parameter names */
  params: string[];
}

// --- Route scanning ---

/**
 * Scan a routes directory and return the route tree.
 */
export function scanRoutes(routesDir: string): ScannedRoute[] {
  if (!existsSync(routesDir)) return [];
  return scanDirectory(routesDir, routesDir, '/');
}

function scanDirectory(
  dir: string,
  rootDir: string,
  basePath: string,
): ScannedRoute[] {
  const routes: ScannedRoute[] = [];
  const entries = readdirSync(dir).sort();

  // Check for page.akash in current directory
  const hasPage = entries.includes('page.akash');
  const hasLayout = entries.includes('layout.akash');
  const hasLoader = entries.some((e) => e === 'loader.ts' || e === 'loader.js');
  const hasGuard = entries.some((e) => e === 'guard.ts' || e === 'guard.js');
  const hasError = entries.includes('error.akash');

  if (hasPage) {
    const routePath = basePath === '/' ? '/' : basePath;
    const relBase = relative(rootDir, dir);

    const route: ScannedRoute = {
      path: routePath,
      componentPath: posixJoin(relBase, 'page.akash'),
      layoutPath: hasLayout ? posixJoin(relBase, 'layout.akash') : undefined,
      loaderPath: hasLoader ? posixJoin(relBase, findFile(dir, 'loader')) : undefined,
      guardPath: hasGuard ? posixJoin(relBase, findFile(dir, 'guard')) : undefined,
      errorPath: hasError ? posixJoin(relBase, 'error.akash') : undefined,
      children: [],
      params: extractParams(routePath),
    };

    // Scan subdirectories for child routes
    for (const entry of entries) {
      const fullPath = join(dir, entry);
      if (statSync(fullPath).isDirectory()) {
        const childPath = buildChildPath(basePath, entry);
        const children = scanDirectory(fullPath, rootDir, childPath);
        route.children.push(...children);
      }
    }

    routes.push(route);
  } else {
    // No page.akash — still scan subdirectories
    for (const entry of entries) {
      const fullPath = join(dir, entry);
      if (statSync(fullPath).isDirectory()) {
        const childPath = buildChildPath(basePath, entry);
        const children = scanDirectory(fullPath, rootDir, childPath);
        routes.push(...children);
      }
    }
  }

  return routes;
}

// --- Route manifest generation ---

/**
 * Generate the virtual module source code for `virtual:akash-routes`.
 * Produces nested RouteConfig[] with children, layouts, guards, and loaders.
 */
export function generateRouteManifest(routes: ScannedRoute[], routesDir: string): string {
  let code = '// Auto-generated by @akashjs/vite-plugin — do not edit\n\n';
  code += 'export const routes = ';
  code += generateRouteArray(routes, 0);
  code += ';\n';
  return code;
}

function generateRouteArray(routes: ScannedRoute[], depth: number): string {
  const indent = '  '.repeat(depth);
  const inner = '  '.repeat(depth + 1);

  let code = '[\n';
  for (const route of routes) {
    code += `${inner}{\n`;
    code += `${inner}  path: ${JSON.stringify(route.path)},\n`;
    code += `${inner}  component: () => import(${JSON.stringify('./' + route.componentPath)}),\n`;
    if (route.layoutPath) {
      code += `${inner}  layout: () => import(${JSON.stringify('./' + route.layoutPath)}),\n`;
    }
    if (route.loaderPath) {
      code += `${inner}  loader: () => import(${JSON.stringify('./' + route.loaderPath)}),\n`;
    }
    if (route.guardPath) {
      code += `${inner}  guard: () => import(${JSON.stringify('./' + route.guardPath)}),\n`;
    }
    if (route.children.length > 0) {
      code += `${inner}  children: ${generateRouteArray(route.children, depth + 2)},\n`;
    }
    code += `${inner}},\n`;
  }
  code += `${indent}]`;
  return code;
}

/**
 * Generate TypeScript declarations for route params.
 */
export function generateRouteTypes(routes: ScannedRoute[]): string {
  let code = '// Auto-generated by @akashjs/vite-plugin — do not edit\n\n';
  code += "declare module '@akashjs/router' {\n";
  code += '  interface RouteParamMap {\n';

  for (const route of flattenRoutes(routes)) {
    if (route.params.length > 0) {
      const paramTypes = route.params
        .map((p) => `${p}: string`)
        .join('; ');
      code += `    '${route.path}': { ${paramTypes} };\n`;
    }
  }

  code += '  }\n';
  code += '}\n';
  return code;
}

// --- Helpers ---

/** Convert directory name to path segment */
function buildChildPath(basePath: string, dirName: string): string {
  let segment = dirName;

  // Route groups: (group) — no URL impact
  if (dirName.startsWith('(') && dirName.endsWith(')')) {
    return basePath;
  }

  // Optional catch-all: [[...rest]]
  if (dirName.startsWith('[[...') && dirName.endsWith(']]')) {
    const name = dirName.slice(5, -2);
    segment = `[[...${name}]]`;
  }
  // Catch-all: [...rest]
  else if (dirName.startsWith('[...') && dirName.endsWith(']')) {
    const name = dirName.slice(4, -1);
    segment = `[...${name}]`;
  }
  // Dynamic param: [param]
  else if (dirName.startsWith('[') && dirName.endsWith(']')) {
    const name = dirName.slice(1, -1);
    segment = `:${name}`;
  }

  return basePath === '/' ? `/${segment}` : `${basePath}/${segment}`;
}

/** Extract parameter names from a route path */
function extractParams(path: string): string[] {
  const params: string[] = [];
  // Match :param, [...param], [[...param]]
  const patterns = [/:(\w+)/g, /\[\.\.\.(\w+)\]/g, /\[\[\.\.\.(\w+)\]\]/g, /\[(\w+)\]/g];
  for (const pattern of patterns) {
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(path)) !== null) {
      if (!params.includes(match[1])) params.push(match[1]);
    }
  }
  return params;
}

/** Flatten nested routes into a flat list */
function flattenRoutes(routes: ScannedRoute[]): ScannedRoute[] {
  const result: ScannedRoute[] = [];
  for (const route of routes) {
    result.push(route);
    if (route.children.length > 0) {
      result.push(...flattenRoutes(route.children));
    }
  }
  return result;
}

/** Find a file with ts or js extension */
function findFile(dir: string, baseName: string): string {
  const entries = readdirSync(dir);
  for (const ext of ['.ts', '.js']) {
    if (entries.includes(baseName + ext)) return baseName + ext;
  }
  return baseName + '.ts';
}

/** Join paths using posix separators (for import paths) */
function posixJoin(...parts: string[]): string {
  return parts.filter(Boolean).join('/').replace(/\\/g, '/');
}
